/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.exceptions;

import io.apimatic.coreinterfaces.http.Context;

/**
 * Exception thrown when an endpoint is not implemented in the mock server.
 */
public class NotImplementedException extends ApiException {
    private static final long serialVersionUID = 1L;

    public NotImplementedException(String reason) {
        super(reason);
    }

    public NotImplementedException(String reason, Context context) {
        super(reason, context);
    }

    @Override
    public String toString() {
        return "NotImplementedException [" + "statusCode=" + getResponseCode() + ", message=" + getMessage() + "]";
    }
}